libraryproject/books/urls.py
from django.urls import path

from . import views

app_name = 'books'
urlpatterns = [
    path(
        'books/',
        views.BookListView.as_view(),
        name='books_list'),
    path(
        'books/update_or_add/',
        views.BookUpdateOrCreateView.as_view(),
        name='book_add'),
    path(
        'books/update_or_add/<int:pk>',
        views.BookUpdateOrCreateView.as_view(),
        name='book_update'),
    path(
        'books/google_books_search/',
        views.GoogleBooksView.as_view(),
        name='google_search'),
]

libraryproject/books_rest/urls.py
from django.urls import path

from . import views

app_name = 'books_rest'

urlpatterns = [
    path('books_rest/books_list/', views.BooksListAPIView.as_view()),
]

libraryproject/libraryproject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('', include('books_rest.urls')),
    path('', RedirectView.as_view(url='/books/'))
]

libraryproject/books/models.py
from datetime import date

from django.db import models
from django.core.validators import MinLengthValidator
from django.core.validators import MaxValueValidator

from django_date_extensions import fields

from .languages import languages


class Book(models.Model):
    title = models.CharField(max_length=256)
    published_date = fields.ApproximateDateField(
        null=True,
        blank=True,
        validators=[
            MaxValueValidator(
                limit_value=date.today)])
    isbn_13 = models.CharField(max_length=13, unique=True, null=True,
                               blank=True, validators=[MinLengthValidator(13)])
    pages = models.PositiveSmallIntegerField(null=True, blank=True)
    cover_link = models.URLField(max_length=400, null=True, blank=True)
    publication_language = models.CharField(max_length=3, choices=languages,
                                            null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['title', 'published_date', 'isbn_13',
                        'pages', 'publication_language'],
                name='unique_joining',
            )
        ]


class Author(models.Model):
    name = models.CharField(max_length=256)
    book = models.ForeignKey(Book, null=True, on_delete=models.CASCADE)

libraryproject/books/forms.py
from django import forms
from django.forms import inlineformset_factory

from . import models


class BookForm(forms.ModelForm):

    class Meta():
        model = models.Book
        fields = '__all__'

    def clean(self):
        super(BookForm, self).clean()
        isbn_13 = self.cleaned_data['isbn_13']
        if isbn_13 is not None:
            if not isbn_13.isnumeric():
                self.add_error('isbn_13', 'Only numbers allowed!')

class AuthorForm(forms.ModelForm):
    name = forms.CharField(label='Author:')
    class Meta():
        model = models.Author
        fields = ('name',)

AuthorsFormSet = inlineformset_factory(
                    models.Book,
                    models.Author,
                    form = AuthorForm,
                    max_num=5,
                    validate_max=True,
                    extra = 3,)


class GoogleForm(forms.Form):
    intitle = forms.CharField(required=False, label='Title contains:')
    inauthor = forms.CharField(required=False, label='Author contains:')
    inpublisher = forms.CharField(required=False, label='Publisher contains:')
    subject = forms.CharField(required=False, label='Categories contain:')
    isbn = forms.CharField(required=False, label='ISBN containts:')
    lccn = forms.CharField(required=False,
                           label='Library of Congress Control Number')
    oclc = forms.CharField(required=False,
                           label='Online Computer Library Center number')

    def clean(self):
        super(GoogleForm, self).clean()
        has_values = len(['' for x in self.cleaned_data.values() if x != ''])
        if not has_values:
            self.add_error('intitle', 'At least one field must be filled')

libraryproject/books/views.py
import requests
import json

from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic import UpdateView
from django.views.generic import FormView
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect

from django_filters.views import BaseFilterView

from . import models
from . import forms
from . import filters
from .data_processing import get_books_model_data
from .data_processing import save_books
from .data_processing import save_form_and_formset
from .prepare_url import prepare_url


class BookListView(BaseFilterView, ListView):

    model = models.Book
    filterset_class = filters.BookFilter


class BookUpdateOrCreateView(UpdateView):
    model = models.Book
    form_class = forms.BookForm
    template_name = 'books/book_update.html'

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()

        if 'pk' in self.kwargs:
            pk = self.kwargs['pk']
            queryset = queryset.filter(pk=pk)
            try:
                obj = queryset.get()
            except queryset.model.DoesNotExist:
                raise Http404(_("No %(verbose_name)s found matching the query") %
                              {'verbose_name': queryset.model._meta.verbose_name})
            return obj
        else:
            return None

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form(self.form_class)
        formset = forms.AuthorsFormSet(instance = self.object)
        return self.render_to_response(self.get_context_data(form=form,
                                                             formset=formset))

    def get_success_url(self):
        return reverse_lazy('books:books_list')

    def form_valid(self, form, formset):
        if self.object is not None:
            form.id = self.object.id
        self.object = save_form_and_formset(form, formset)
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, formset):
        return self.render_to_response(self.get_context_data(form=form,
                                                            formset=formset))

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        formset = forms.AuthorsFormSet(self.request.POST,
                                       instance = self.object)

        if form.is_valid() and formset.is_valid():
            return self.form_valid(form, formset)
        else:
            return self.form_invalid(form, formset)


class GoogleBooksView(FormView):
    template_name = 'books/google_books_search.html'
    model = models.Book
    form_class = forms.GoogleForm

    def form_valid(self, form):
        url = prepare_url(form)
        client = requests.session()
        response = client.get(url)

        if response.json()['totalItems'] == 0:
            return HttpResponseRedirect(self.get_success_url())

        books_list = response.json()['items']
        books_model_data_list = get_books_model_data(books_list)
        save_books(books_model_data_list)
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse_lazy('books:books_list')

libraryproject/books_rest/views.py
from rest_framework import generics
from django_filters import rest_framework as filters

from . import filters
from . import serializers

from books import models


class BooksListAPIView(generics.ListAPIView):
    queryset = models.Book.objects.all()
    serializer_class = serializers.BooksSerializer
    filterset_class = filters.BookFilter

libraryproject/books/templates/books/book_list.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
  <div class="col-sm-10 blogShort">
      <form method="GET">
        <h3>Filter books:</h3>
        <br>
        {% bootstrap_form filter.form layout='horizontal' %}

        <br>
        <br>
        <input class="btn btn-default" type="submit" value="Filter!">
        <a href="{%url 'books:books_list' %}">
          <button type="button" class="btn btn-default">Reset Filters!</button>
        </a>
      </form>
      <br>
    </div>
</div>
<div class="container">
  <a href="{%url 'books:book_add' %}">
    <button type="button" class="btn btn-default">Add new book</button>
  </a>
  <a href="{%url 'books:google_search' %}">
    <button type="button" class="btn btn-default">Search in google api</button>
  </a>
</div>
<div class="container">
    <table class="table-sm table-bordered table-striped">
      <thead>
        <tr>
          <th class="text-center">Title</th>
          <th class="text-center">Authors</th>
          <th class="text-center">Published</th>
          <th class="text-center">ISBN</th>
          <th class="text-center">Pages</th>
          <th class="text-center">Link to cover</th>
          <th class="text-center">Language</th>
        </tr>
      </thead>
      <tbody>
        {% for book in book_list %}
        <tr>
          <td class="text-center"> {{book.title}}</td>
          <td class="text-center">
            {% for author in book.author_set.all %}
              {{author.name}} <br>
            {% endfor %}
          </td>
          <td class="text-center"> {{book.published_date}}</td>
          <td class="text-center"> {{book.isbn_13}}</td>
          <td class="text-center"> {{book.pages}}</td>
          <td class="text-center">
            {% if book.cover_link %}
              <img src="{{book.cover_link}}" alt="no-cover" width="50" height="60">
            {% else %}
            no cover
            {% endif %}
          </td>
          <td class="text-center"> {{book.publication_language}}</td>
          <td class="text-center">
            <a href="{%url 'books:book_update' book.id %}">
              <button type="button" class="btn btn-default">Edit</button>
            </a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

{% endblock %}

libraryproject/books/templates/books/book_update.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="col-sm-10">
  <h1>Edit book:</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% bootstrap_formset formset layout='horizontal' %}
    {% if form.title.value %}
      <input class="btn btn-default" type="submit" value="Edit!">
    {% else %}
      <input class="btn btn-default" type="submit" value="Create!">
    {% endif %}

  </form>
</div>
{% endblock %}

libraryproject/books/templates/books/google_books_search.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="col-sm-10">
  <h1>Search for:</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}

      <input class="btn btn-default" type="submit" value="Search!">


  </form>
</div>
{% endblock %}

libraryproject/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    {% block content %}
    {% endblock %}
  </body>
</html>